language: python
cache: apt
notifications:
  email: false

# ======= Linux ========
os: linux
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.7-dev
  - 3.8
  - 3.8-dev


git:
  depth: 3
  quiet: False

#branches:
#  only:
#    - master
#    - develop

addons:
  apt:
    packages:
      - gcc
      - gfortran
      - libblas-dev
      - liblapack-dev
jobs:
#  allow_failures:
#     - os: osx
#     - os: windows

  include:
#    - name: "Python 2.7 on Xenial"
#      python: 2.7
#      dist: xenial

#    - name: "Python 2.7 on Bionic"
#      python: 2.7
#      dist: bionic

    - name: "Python 3.5 on Bionic"
      python: 3.5
      dist: bionic

    - name: "Python 3.6  on Bionic"
      python: 3.6
      dist: bionic

    - name: "Python 3.7  on Bionic"
      python: 3.7
      dist: bionic

    - name: "Python 3.8 on Bionic"
      python: 3.8
      dist: bionic
      after_success:
        - codecov # submit coverage only here.

    - name: "Python 3.7-dev on Bionic"
      python: 3.7-dev
      dist: bionic

    - name: "Python 3.8-dev on Bionic"
      python: 3.8-dev
      dist: bionic

# ======= OSX ========
# reference: https://docs.travis-ci.com/user/reference/osx/
#    - name: "Python 2.7.14 on macOS 10.13" # not running recommendation tests.
#      os: osx
#      osx_image: xcode9.3  # Python 2.7.14_2 running on macOS 10.13
#      language: shell       # 'language: python' is an error on Travis CI macOS
#      before_install:
#        - python --version
#        - python -m pip install -U pip --user
#      install:  # this needs a special flag.
#        - pip install -U .[testing] --user
#      script: python -m pytest

    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip install cython  # errors without this
      install:  # need to use pip3 to ensure we're not accidentally using python 2.7
        - pip3 install -U .[testing]
        - pip3 install -U .[recommend]
        - pip3 install .
      script: python3 -m pytest

    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
      install:
        - pip3 install -U .[testing]
        - pip3 install -U .[recommend]
        - pip3 install .
      script: python3 -m pytest

    - name: "Python 3.7.4 on macOS 10.14"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4 (also on xcode10.3)
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
      install:
        - pip3 install -U .[testing]
        - pip3 install -U .[recommend]
        - pip3 install .
      script: python3 -m pytest

##  ====== WINDOWS =========
#    - name: "Python 2.7 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell # 'language: python' errors Travis CI Windows
#      before_install:
#        - choco install python2
#        - python --version
#        - python -m pip install -U pip
#       install: 
#         - pip install -U .[testing]
#         - pip install .
#      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
#
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install -U pip
        - pip install numpy cython
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install -U pip
        - pip install numpy cython
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install -U pip
        - pip install numpy cython
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: "Python 3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8
        - python --version
        - python -m pip install -U pip
        - pip install numpy cython
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


before_install:
  - python --version
  - pip install -U pip
  # if numpy or cython is missing, errors come up with installation.
  - pip install numpy cython

install:
  - pip install .
  - pip install .[testing]
  - pip install .[recommend]

script: pytest
